//import '@/styles/blocks.scss'; // <-- Import block styles from WordPress.
import { AsideProvider } from "@/context/AsideContext";
import '@/styles/globals.css';
import { WordPressBlocksProvider, fromThemeJson } from '@faustwp/blocks';
import { FaustProvider } from '@faustwp/core';
import "@wordpress/block-library/build-style/style.css";
import { useRouter } from 'next/router';
import '../../faust.config.js'; // <-- Faust config file, required for FaustProvider to work.
import '../../globalStylesheet.css'; // <-- Generated by pnpm run generate
import ThemeProvider from "../components/theme/ThemeProvider";
import themeJson from "../theme.json";
import blocks from '../wp-blocks';

export default function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <AsideProvider>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        transition={true}
        //disableTransitionOnChange
      >
        <FaustProvider pageProps={pageProps}>
          <WordPressBlocksProvider
            config={{
              blocks,
              theme: fromThemeJson(themeJson),
            }}
          >
            <Component {...pageProps} key={router.asPath} />
          </WordPressBlocksProvider>
        </FaustProvider>
      </ThemeProvider>
    </AsideProvider>
  );
}